# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
    branches:
      - main
  schedule:
    - cron: "*/5 * * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger a publish
        run: curl -X POST ${{ secrets.END_POINT_NAME }}
