name: AUTOMATE_DEVTO

on:
  push:
    branches:
      - main
  schedule:
    - cron: "*/5 * * * *"

jobs:
  start:
    name: Start
    runs-on: ubuntu-latest
    container:
      image: node:stretch-slim

    steps:
      - name: Initialize Node.js project
        run: npm init -y
      - name: Install packages
        run: npm i
      - name: Run
        run: npm run start:test_run
